BROKER: {MQTT_HOST: localhost, MQTT_PORT: '1883', MQTT_PUB_CH: /OPENHAB, MQTT_SUB_CH: /RASPBERRY01}
DEVICES:
  DEVICE01:
    I2C_ADDRESS: '0x26'
    NAME: DEVICE1
    Port0: {HWID: '0', MODE: BINARY-IN, NAME: GPIO100, OFF_VALUE: 'OFF', ON_VALUE: 'ON'}
    Port1: {HWID: '1', MODE: BINARY-IN, NAME: GPIO101, OFF_VALUE: 'OFF', ON_VALUE: 'ON'}
    RASPBERRY_REV: '1'
    TYPE: MCP23017
  DEVICE03:
    I2C_ADDRESS: '0x33'
    NAME: DEVICE3
    PORT300: {HWID: '0', MODE: BINARY-IN, NAME: GPIO301, OFF_VALUE: 'OFF', ON_VALUE: 'ON'}
    RASPBERRY_REV: '1'
    TYPE: MCP23017
  DEVICE04:
    I2C_ADDRESS: '0x44'
    NAME: DEVICE4
    PORT400: {NAME: PORT44}
    RASPBERRY_REV: '1'
    TYPE: MCP23017
  DEVICE05:
    I2C_ADDRESS: '0x55'
    NAME: DEVICE5
    Port500: {NAME: PORT55}
    RASPBERRY_REV: '1'
    TYPE: MCP23017
GENERAL: {LOGFILE: /var/log/gpio2mqtt.log, LOGMODE: INFO, UPDATE: '0.01'}
